### PR TITLE
CenTecConnector: Fix Clip slide.

### PR DESCRIPTION
**Pull request by vifino**
The Clip slide was missing and I thought it was overly complicated, so I simplified it and made it work.

It has a 8 degree tilt inwards which looks good to me

BTW: Could you consider running a formatter on the code? Something like [scadformat](https://github.com/hugheaves/scadformat/) for example.

### CODE REVIEW

**Comment by ostat** [comment]
Thanks for taking to time to make the changes and submit the PR.
I think this is now working. Not sure when I fixed it. 
I don't have a CenTec adapter to test, but the current version was tested by someone else. to fit ok do you have an adapter to test the fit with the modified slide?

Originally I did try making the slide with a cube. But using the pipe allowed it to be curved with lip taper.

image

**Comment by vifino** [comment]
The versions I printed before the PR seemingly had no slide whatsoever and weren't very easy to attach.
My modified variant is very easy and quickly attachable and works very well with 3D printed Centek Hose Adapters, knock-offs from China and Bosch C35 adapters.

**Comment by vifino** [comment]
For reference, [these Centec/Bosch/Kärcher C35 hose adapters](https://www.printables.com/model/112236-boschkarcher-c35-male-adapter-for-32mm-hose) worked the best for me (when scaled up in x/y by +1.5%).

They fit just like the originals.

**Comment by ostat** [comment]
> The versions I printed before the PR seemingly had no slide whatsoever and weren't very easy to attach.
> 
> My modified variant is very easy and quickly attachable and works very well with 3D printed Centek Hose Adapters, knock-offs from China and Bosch C35 adapters.

Would you be able to attach that stl?

Also would you mind trying the latest version and seeing what it looks like in the slicer?

I will also pull your branch and take a look.

**Comment by ostat** [comment]
I had a look at this, the clip slide was not working in the version you had. I prefer the original clip slide so I will keep that one.
If you think its not working could you please re-open?

**Pull request closed without merging**
